hwi_oauth:
  # list of names of the firewalls in which this bundle is active, this setting MUST be set
  firewall_names: [main]
  # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
  resource_owners:
    auth0:
      type: oauth2
      class:               'App\Auth0ResourceOwner'
      client_id:           "%env(AUTH0_CLIENT_ID)%"
      client_secret:       "%env(AUTH0_CLIENT_SECRET)%"
      base_url:            "https://%env(AUTH0_DOMAIN)%"
      scope: "openid profile email"